# Generated by Django 5.0.4 on 2025-01-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
