# Generated by Django 5.0.4 on 2025-02-12 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth import get_user_model



def get_default_user():
    return get_user_model().objects.first().id


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_writer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(default=get_default_user,on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
