# Generated by Django 5.1.5 on 2025-02-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_slug_delete_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='slug',
        ),
    ]
