# Generated by Django 5.1.5 on 2025-02-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articles_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='slug',
        ),
    ]
