# Generated by Django 5.1.5 on 2025-03-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_articles_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='slug',
        ),
    ]
