services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: |
      echo "Installing Python dependencies..."
      pip install -r requirements.txt

      echo "Installing Node.js dependencies..."
      cd theme/static_src  # Navigate to correct directory
      npm install
      npm run build:tailwind  # Ensure this script exists in package.json
      cd ../../  # Move back to project root

      echo "Collecting static files..."
      python manage.py collectstatic --noinput

      echo "Applying database migrations..."
      python manage.py migrate
    startCommand: "gunicorn tryDjango.wsgi:application"
    envVars:
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-for-django
          property: connectionString

databases:
  - name: postgres-for-django
    plan: free
    databaseName: postgres_for_django
    user: postgres_for_django_user
