# Generated by Django 5.1.5 on 2025-01-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=50)),
                ('current_leader', models.CharField(max_length=50)),
                ('establish_in', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mumbai_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_constitution_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(max_length=10)),
                ('parties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Politics.parties')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('candidate_age', models.IntegerField(max_length=2)),
                ('from_which_assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Politics.mumbai_region')),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Politics.parties')),
            ],
        ),
    ]
