# Generated by Django 5.1.5 on 2025-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Politics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mumbai_region',
            name='distric',
            field=models.CharField(default='Mumbai', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mumbai_region',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
