# Generated by Django 5.1.5 on 2025-01-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Politics', '0003_alter_mumbai_region_distric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mumbai_region',
            name='parties',
        ),
    ]
