# Generated by Django 5.0.4 on 2025-01-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Politics', '0004_remove_mumbai_region_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='total_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parties',
            name='total_vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
